### ISSUE TITLE
Please update deprecated fields / Costco

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-costco#14]
Please update:

mortgage.application.credit_rating ---> credit_rating

**Comment by zalary** [comment]
also needed to support 
mortgage.application.bankruptcy --> mortgage.bankruptcy.was_declared

**Comment by zalary** [comment]
resolved with PR #15 which should have auto-closed this.

**Comment by kcaponeAP** [comment]
I still see credit rating as deprecated on docs.leadconduit.com, can this be updated?

http://docs.leadconduit.com/fields?q=costco%20inbound

**Comment by zalary** [comment]
do we have a recent example of a costco submission?

**Comment by kcaponeAP** [comment]
https://next.leadconduit.com/events/55bc1d66b192c332634a62b7?source_id=5419e133852bc7460e27745d&type=source&start=2015-07-01&end=2015-07-31
